services:

  cloudcmd:
    image: coderaiser/cloudcmd:latest
    container_name: cloudcmd
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ~:/root
      - /:/mnt/fs

      