services:

  cloudcmd:
    image: coderaiser/cloudcmd:latest
    container_name: cloudcmd
    restart: unless-stopped
    ports:
      - "8100:8000"
    volumes:
      - ~:/root
      - /:/mnt/fs
    environment:
      - CLOUDCMD_AUTH=true
      - CLOUDCMD_USERNAME=User
      - CLOUDCMD_PASSWORD=p4ssw0rd
      
